[window]
startup_mode = "Maximized"
title = ""
decorations = "Buttonless"
opacity = 8

[general]
import = [
    "~/.config/alacritty/themes/themes/rose_pine_moon.toml"
]

[colors]
primary = { background = "#040404" }

[font]
normal = { family = "Hack Nerd Font Mono", style = "Regular"}
size = 28

[env]
TERM = "tmux-256color"
