# ~/.aerospace.toml

# Gaps between windows
gaps.inner.horizontal = 12
gaps.inner.vertical = 12
gaps.outer.left = 12
gaps.outer.bottom = 12
gaps.outer.top = 12
gaps.outer.right = 12

[mode.main.binding]
# Switch workspaces 1–9
"alt-1" = "workspace 1"
"alt-2" = "workspace 2"
"alt-3" = "workspace 3"
"alt-4" = "workspace 4"
"alt-5" = "workspace 5"
"alt-6" = "workspace 6"
"alt-7" = "workspace 7"
"alt-8" = "workspace 8"
"alt-9" = "workspace 9"

# Move focused window and follow it
"shift-alt-1" = "move-node-to-workspace 1"
"shift-alt-2" = "move-node-to-workspace 2"
"shift-alt-3" = "move-node-to-workspace 3"
"shift-alt-4" = "move-node-to-workspace 4"
"shift-alt-5" = "move-node-to-workspace 5"
"shift-alt-6" = "move-node-to-workspace 6"
"shift-alt-7" = "move-node-to-workspace 7"
"shift-alt-8" = "move-node-to-workspace 8"
"shift-alt-9" = "move-node-to-workspace 9"

[[on-window-detected]]
if.app-id = "com.apple.finder"
run = "move-node-to-workspace 6"

[[on-window-detected]]
if.app-id = "org.outline.macos.client"
run = "move-node-to-workspace 6"

[[on-window-detected]]
if.app-id = "com.electron.ollama"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "md.obsidian"
run = "move-node-to-workspace 1"

[[on-window-detected]]
if.app-id = "org.alacritty"
run = "move-node-to-workspace 3"

[[on-window-detected]]
if.app-id = "org.mozilla.firefox"
run = "move-node-to-workspace 4"

[[on-window-detected]]
if.app-id = "ru.keepcoder.Telegram"
run = "move-node-to-workspace 5"

[[on-window-detected]]
if.app-id = "com.electron.dockerdesktop"
run = "move-node-to-workspace 2"

[[on-window-detected]]
if.app-id = "com.microsoft.VSCode"
run = "move-node-to-workspace 2"
