set -g prefix C-Space
set -g default-terminal "tmux-256color"
set-option -sa terminal-overrides ',*:Tc'  # <== ВАЖНО для truecolor

set-option -g status-bg black
set-option -g status-fg grey
set -g status-left "#[fg=white,bold]#S "
set -g status-right ""
set-option -g status-position top

set -g mouse on

set -g status-interval 1
set -g status-justify left

set -g status-left-length 40
set -g status-right-length 150

set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-window-option -g mode-keys vi

bind r source-file ~/.tmux.conf

bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

bind -n M-1 select-window -t 1
bind -n M-2 select-window -t 2

bind -r C-S-h resize-pane -L 2
bind -r C-S-j resize-pane -D 2
bind -r C-S-k resize-pane -U 2
bind -r C-S-l resize-pane -R 2

bind -n C-S-c new-window
bind -n C-S-x kill-window

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-fzf'

# Transparent bg
set -g status-style bg=default
set -g pane-border-style fg="#727169"
set -g pane-active-border-style fg="#7e9cd8"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
