#!/bin/bash
# Yabai config

# Layout
yabai -m config layout bsp

# Window placement
yabai -m config window_placement second_child

# Padding
yabai -m config top_padding 8
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config window_gap 8

# Mouse settings
yabai -m config focus_follows_mouse autoraise
yabai -m config mouse_modifier fn
yabai -m config mouse_action1 move
yabai -m config mouse_action2 resize
yabai -m config mouse_follows_focus on

# Disable specific apps
yabai -m rule --add app="^System Settings$" manage=off
yabai -m rule --add app="^Calculator$" manage=off
yabai -m rule --add app="^Shottr$" manage=off
yabai -m rule --add app="^ProtonVPN$" manage=off
yabai -m rule --add app="^Raycast$" manage=off
yabai -m rule --add app="^WhatsApp$" manage=off

# Space assignments
yabai -m rule --add app="^Obsidian$"  space=1
yabai -m rule --add app="^Caido$"     space=2
yabai -m rule --add app="^Alacritty$" space=3
yabai -m rule --add app="^Firefox$"   space=4
yabai -m rule --add app="^Telegram$"  space=5
yabai -m rule --add app="^Finder$"    space=6
yabai -m rule --add app="^Happ$"      space=7

# Window shadows
yabai -m config window_shadow off

# Sketchybar external bar
yabai -m config external_bar all:29:0

# Sketchybar integration
yabai -m signal --add event=window_focused action="sketchybar --trigger front_app_switched INFO=\"\$(yabai -m query --windows --window | jq -r '.app // \"Finder\"')\""
yabai -m signal --add event=space_changed action="sketchybar --trigger space_change"
yabai -m signal --add event=window_created action="sketchybar --trigger front_app_switched INFO=\"\$(yabai -m query --windows --window | jq -r '.app // \"Finder\"')\"; sketchybar --trigger space_windows_change"
yabai -m signal --add event=window_destroyed action="sketchybar --trigger front_app_switched INFO=\"\$(yabai -m query --windows --window | jq -r '.app // \"Finder\"')\"; sketchybar --trigger space_windows_change"
yabai -m signal --add event=window_minimized action="sketchybar --trigger front_app_switched INFO=\"\$(yabai -m query --windows --window | jq -r '.app // \"Finder\"')\"; sketchybar --trigger space_windows_change"
yabai -m signal --add event=window_deminimized action="sketchybar --trigger front_app_switched INFO=\"\$(yabai -m query --windows --window | jq -r '.app // \"Finder\"')\"; sketchybar --trigger space_windows_change"

# Borders
borders active_color=0xff74c7ec inactive_color=0xffcba6f7 width=6.0 hidpi=on &

echo "yabai configuration loaded"
